services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pg_data: