"""add fs_uniquifier to User model

Revision ID: 1bc9a9b7f715
Revises: 088ca6fb48eb
Create Date: 2025-02-26 09:52:39.809012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc9a9b7f715'
down_revision: Union[str, None] = '088ca6fb48eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fs_uniquifier', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['fs_uniquifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'fs_uniquifier')
    # ### end Alembic commands ###
