"""add has_original to media

Revision ID: 7b62394fd6c3
Revises: 9f978053b5d9
Create Date: 2025-03-23 12:40:33.345005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b62394fd6c3'
down_revision: Union[str, None] = '9f978053b5d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('has_original', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'has_original')
    # ### end Alembic commands ###
