"""add permissions field to roles table

Revision ID: 9f978053b5d9
Revises: 4648901df73d
Create Date: 2025-02-28 17:43:42.722875

"""
from typing import Sequence, Union

import flask_security
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f978053b5d9'
down_revision: Union[str, None] = '4648901df73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', flask_security.datastore.AsaList(), nullable=True))
    op.add_column('roles', sa.Column('update_datetime', sa.DateTime(), server_default=sa.text("timezone('utc', now())"), nullable=False))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('roles', 'update_datetime')
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
